name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Linting step
    - name: Lint with flake8
      run: |
        # Run flake8 for error checks and code complexity analysis
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

    # Testing step
    - name: Run unit tests with nose
      run: |
        # Run unit tests with nose and measure coverage
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
